### ISSUE TITLE
export dashboards issue

### ISSUE THREAD

**Issue by agithomas** [elastic/elastic-package#1354]
Observed with versions : 8.8.0, 8.8.2
Package used : Memcached

Steps to reproduce the issue: 
1. Start the stack with the command `elastic-package stack up --version 8.8.2 -v -d`
2. Add a Memcached integration
3. Export the dashboard with the command `elastic-package export dashboards`. Choose `[Metrics Memcached] Overview`
4. Update the changelog , manifest.yml file to next version for memached. Run - `elastic-package build; elastic-package stack up -v -d --services package-registry`
5. Go to kibana -> Integration package -> upgrade Memcached package
6. You will notice the error as below
<img width="344" alt="image" src="https://github.com/elastic/elastic-package/assets/101976829/eccf39a1-d487-49de-94ed-a03e4aa80830">

**Comment by agithomas** [comment]
> @agithomas can you try to install the package with `elastic-package install` and check the error reported there?

Please find the error below

```
agikthomas@service-integration-dev-idc-1:~/go/src/github.com/elastic/integrations/packages/memcached$ elastic-package install memcached
Install the package
Error: can't install the package: can't install the package: could not install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Migration function for version 7.13.1 threw an error"}
```

**Comment by mrodm** [comment]
I was able to reproduce this error, when that happened this error was in Kibana container:
`Caused by:
TypeError: Cannot read properties of undefined (reading 'layers')`

this is the whole stack trace:
```
[2023-07-14T10:37:17.805+00:00][ERROR][savedobjects-service] TypeError: Cannot read properties of undefined (reading 'layers')
    at commonRenameOperationsForFormula (/usr/share/kibana/node_modules/@kbn/lens-plugin/server/migrations/common_migrations.js:29:78)
    at Object.7.13.1 (/usr/share/kibana/node_modules/@kbn/lens-plugin/server/embeddable/make_lens_embeddable_factory.js:25:91)
    at migrateFn (/usr/share/kibana/node_modules/@kbn/embeddable-plugin/common/lib/migrate.js:23:48)
    at migrations.<computed> (/usr/share/kibana/node_modules/@kbn/embeddable-plugin/common/lib/get_all_migrations.js:34:10)
    at /usr/share/kibana/node_modules/@kbn/dashboard-plugin/server/dashboard_saved_object/migrations/migrate_by_value_dashboard_panels.js:50:29
    at Array.forEach (<anonymous>)
    at /usr/share/kibana/node_modules/@kbn/dashboard-plugin/server/dashboard_saved_object/migrations/migrate_by_value_dashboard_panels.js:43:10
    at Object.tryTransformDoc [as transform] (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/utils.js:36:22)
    at DocumentUpgradePipeline.run (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/pipelines/upgrade_pipeline.js:174:21)
    at DocumentMigrator.transform (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/document_migrator.js:129:18)
    at DocumentMigrator.migrate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/document_migrator.js:59:16)
    at KibanaMigrator.migrateDocument (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/kibana_migrator.js:150:34)
    at /usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/lib/repository.js:463:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 2)
    at SavedObjectsRepository.bulkCreate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/lib/repository.js:404:33)
    at SavedObjectsClient.bulkCreate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/saved_objects_client.js:37:12)
    at createSavedObjects (/usr/share/kibana/node_modules/@kbn/core-saved-objects-import-export-server-internal/src/import/lib/create_saved_objects.js:113:32)
    at importSavedObjectsFromStream (/usr/share/kibana/node_modules/@kbn/core-saved-objects-import-export-server-internal/src/import/import_saved_objects.js:110:36)
    at retryImportOnConflictError (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:201:18)
    at installKibanaSavedObjects (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:232:9)
    at installKibanaAssets (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:109:27)
    at installKibanaAssetsAndReferences (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:135:26)
[2023-07-14T10:37:18.071+00:00][WARN ][plugins.fleet] Failure to install package [memcached]: [Error: Migration function for version 7.13.1 threw an error]
[2023-07-14T10:37:18.466+00:00][ERROR][plugins.fleet] rolling back to memcached-1.0.0 after error installing memcached-1.0.1
[2023-07-14T10:37:20.494+00:00][ERROR][plugins.fleet] Error: Migration function for version 7.13.1 threw an error
    at Object.tryTransformDoc [as transform] (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/utils.js:49:13)
    at DocumentUpgradePipeline.run (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/pipelines/upgrade_pipeline.js:174:21)
    at DocumentMigrator.transform (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/document_migrator.js:129:18)
    at DocumentMigrator.migrate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/document_migrator.js:59:16)
    at KibanaMigrator.migrateDocument (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/kibana_migrator.js:150:34)
    at /usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/lib/repository.js:463:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 2)
    at SavedObjectsRepository.bulkCreate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/lib/repository.js:404:33)
    at SavedObjectsClient.bulkCreate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/saved_objects_client.js:37:12)
    at createSavedObjects (/usr/share/kibana/node_modules/@kbn/core-saved-objects-import-export-server-internal/src/import/lib/create_saved_objects.js:113:32)
    at importSavedObjectsFromStream (/usr/share/kibana/node_modules/@kbn/core-saved-objects-import-export-server-internal/src/import/import_saved_objects.js:110:36)
    at retryImportOnConflictError (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:201:18)
    at installKibanaSavedObjects (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:232:9)
    at installKibanaAssets (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:109:27)
    at installKibanaAssetsAndReferences (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:135:26)
Caused by:
TypeError: Cannot read properties of undefined (reading 'layers')
    at commonRenameOperationsForFormula (/usr/share/kibana/node_modules/@kbn/lens-plugin/server/migrations/common_migrations.js:29:78)
    at Object.7.13.1 (/usr/share/kibana/node_modules/@kbn/lens-plugin/server/embeddable/make_lens_embeddable_factory.js:25:91)
    at migrateFn (/usr/share/kibana/node_modules/@kbn/embeddable-plugin/common/lib/migrate.js:23:48)
    at migrations.<computed> (/usr/share/kibana/node_modules/@kbn/embeddable-plugin/common/lib/get_all_migrations.js:34:10)
    at /usr/share/kibana/node_modules/@kbn/dashboard-plugin/server/dashboard_saved_object/migrations/migrate_by_value_dashboard_panels.js:50:29
    at Array.forEach (<anonymous>)
    at /usr/share/kibana/node_modules/@kbn/dashboard-plugin/server/dashboard_saved_object/migrations/migrate_by_value_dashboard_panels.js:43:10
    at Object.tryTransformDoc [as transform] (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/utils.js:36:22)
    at DocumentUpgradePipeline.run (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/pipelines/upgrade_pipeline.js:174:21)
    at DocumentMigrator.transform (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/document_migrator.js:129:18)
    at DocumentMigrator.migrate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/document_migrator/document_migrator.js:59:16)
    at KibanaMigrator.migrateDocument (/usr/share/kibana/node_modules/@kbn/core-saved-objects-migration-server-internal/src/kibana_migrator.js:150:34)
    at /usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/lib/repository.js:463:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 2)
    at SavedObjectsRepository.bulkCreate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/lib/repository.js:404:33)
    at SavedObjectsClient.bulkCreate (/usr/share/kibana/node_modules/@kbn/core-saved-objects-api-server-internal/src/saved_objects_client.js:37:12)
    at createSavedObjects (/usr/share/kibana/node_modules/@kbn/core-saved-objects-import-export-server-internal/src/import/lib/create_saved_objects.js:113:32)
    at importSavedObjectsFromStream (/usr/share/kibana/node_modules/@kbn/core-saved-objects-import-export-server-internal/src/import/import_saved_objects.js:110:36)
    at retryImportOnConflictError (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:201:18)
    at installKibanaSavedObjects (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:232:9)
    at installKibanaAssets (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:109:27)
    at installKibanaAssetsAndReferences (/usr/share/kibana/node_modules/@kbn/fleet-plugin/server/services/epm/kibana/assets/install.js:135:26)
```

**Comment by jsoriano** [comment]
Exported dashboards in 8.8 seem to have a slightly different format, that maybe don't play well with the [transformations](https://github.com/elastic/elastic-package/blob/6d1d182de27425ba56b36b01fab99f88c486651a/internal/export/dashboards.go) `elastic-package` does when exporting.

Some changes seen:
```diff
                             "datasourceStates": {
-                                "indexpattern": {
+                                "formBased": {
                                     "layers": {
...
-                        "visualizationType": "lnsMetric"
+                        "visualizationType": "lnsLegacyMetric"
                     },
-                    "enhancements": {}
+                    "enhancements": {},
+                    "type": "lens"
                 },
...
-    "migrationVersion": {
-        "dashboard": "8.3.0"
-    },
...
+    "managed": false,
-    "type": "dashboard"
+    "type": "dashboard",
+    "typeMigrationVersion": "8.7.0"

```

**Comment by mrodm** [comment]
Tried this process also with 8.7.1 version, and the dashboard could be exported and installed without any issues.

**Comment by jsoriano** [comment]
Trying a (not ideal) workaround: https://github.com/elastic/elastic-package/pull/1356

**Comment by nicpenning** [comment]
I spent about 5 hours trying to debug this and should have just checked the issues here!

You can create a new dashboard with a simple visualization added to it and it will fail with:
(as mentioned above)

```
Error: error running package asset tests: could not complete test run: can't install the package: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Migration function for version 7.13.1 threw an error"}
```

I also found that if I try to export a dashboard that was made for 8.7.0, this is also an issue. For example, I ran `elastic-package export dashboards` for `[System] Windows Overview (ID: system-Windows-Dashboard)` and then ran `elastic-package test` and received the same error above. So it seems you cannot export dashboards successfully at this point in time.

I will attempt some work arounds manually and whatever ones you implement as well.

**Comment by jsoriano** [comment]
Tried to import one of the failing dashboards, extracted from a package, and it seems to work, so I wonder if this is some combination with Fleet :thinking: 

These are the steps I followed:
* Extract the dashboard file from the package.
* Remove newlines and rename the file to `.ndjson`.
* Installed the dashboard using the API:
```
curl -k -XPOST --form file=@/tmp/foo.ndjson -u elastic:changeme -H "kbn-xsrf: true" https://localhost:5601/api/saved_objects/_import
{"successCount":1,"success":true,"warnings":[],"successResults":[{"type":"dashboard","id":"apache-Metrics-Apache-HTTPD-server-status","meta":{"title":"[Metrics Apache] Overview","icon":"dashboardApp"}}]}
```

Installing the package with this dashboard fails:
```
Error: can't install the package: could not zip-install package; API status code = 500; response body = {"statusCode":500,"error":"Internal Server Error","message":"Migration function for version 7.13.1 threw an error"}
```

Package with failing dashboard: [apache-1.14.0.zip](https://github.com/elastic/elastic-package/files/12066645/apache-1.14.0.zip)
Dashboard extracted, with newlines removed: [dashboard.ndjson](https://github.com/elastic/elastic-package/files/12066731/dashboard.ndjson.txt)

**Comment by juliaElastic** [comment]
> Some changes seen:
> 
> ```diff
>                              "datasourceStates": {
> -                                "indexpattern": {
> +                                "formBased": {
>                                      "layers": {
> ...
> -                        "visualizationType": "lnsMetric"
> +                        "visualizationType": "lnsLegacyMetric"
>                      },
> -                    "enhancements": {}
> +                    "enhancements": {},
> +                    "type": "lens"
>                  },
> ...
> -    "migrationVersion": {
> -        "dashboard": "8.3.0"
> -    },
> ...
> +    "managed": false,
> -    "type": "dashboard"
> +    "type": "dashboard",
> +    "typeMigrationVersion": "8.7.0"
> ```

Checked the stacktrace, and it fails at this line in lens migration: https://github.com/elastic/kibana/blob/b5b486c9a491fa36d7ba4986b64376e32fd68ee3/x-pack/plugins/lens/server/migrations/common_migrations.ts#L56

The code looks tries to reference `indexpattern.layers`, which is undefined. 
Is it right that the migration 7.13 runs at all?
